backend:
  name: git-gateway
  branch: main # Change to "master" if your main branch is called master

media_folder: "assets/images" # Where the uploaded files will be saved in the repo
public_folder: "/assets/images" # The path used in the generated content

collections:
  - name: "projects"
    label: "Portfolio Projects"
    folder: "content/projects" # Folder where markdown files will be saved
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Project Title", name: "title", widget: "string"}
      - {label: "Categories (space separated)", name: "categories", widget: "string"}
      - {label: "Short Description (Lead)", name: "description", widget: "text"}
      - {label: "Main Content", name: "body", widget: "markdown"}
